@startuml
actor actor



AbstractApplicationContext-> AbstractApplicationContext:registerBeanPostProcessors(beanFactory)
AbstractApplicationContext-> PostProcessorRegistrationDelegate:invokeBeanFactoryPostProcessors
PostProcessorRegistrationDelegate-> PostProcessorRegistrationDelegate:invokeBeanFactoryPostProcessors
PostProcessorRegistrationDelegate-> ConfigurationClassPostProcessor:postProcessBeanDefinitionRegistry(registry)
ConfigurationClassPostProcessor-> ConfigurationClassPostProcessor:processConfigBeanDefinitions(registry)
ConfigurationClassPostProcessor-> ConfigurationClassBeanDefinitionReader:loadBeanDefinitions
ConfigurationClassBeanDefinitionReader-> ConfigurationClassBeanDefinitionReader:loadBeanDefinitionsForConfigurationClass
ConfigurationClassBeanDefinitionReader-> ConfigurationClassBeanDefinitionReader:registerBeanDefinitionForImportedConfigurationClass
ConfigurationClassBeanDefinitionReader-> ConfigurationClassBeanDefinitionReader:loadBeanDefinitionsForBeanMethod(beanMethod)
ConfigurationClassBeanDefinitionReader-> ConfigurationClassBeanDefinitionReader:loadBeanDefinitionsFromImportedResources(configClass.getImportedResources())
ConfigurationClassBeanDefinitionReader-> ConfigurationClassBeanDefinitionReader:loadBeanDefinitionsFromRegistrars(configClass.getImportBeanDefinitionRegistrars())
@enduml